In [1]:
import sys
sys.path.append('../src')

In [2]:
import pickle
import os
import collections
import numpy as np
import math
import encoder_decoder_uttt as ed
from utictactoe_board import board as c_board
import copy
import torch
import torch.multiprocessing as mp
from alpha_net_uttt import ConnectNet
import datetime
import logging
from tqdm import tqdm

In [3]:
net = ConnectNet()

In [4]:
cuda = torch.cuda.is_available()

In [5]:
net.cuda()

ConnectNet(
  (conv): ConvBlock(
    (conv1): Conv2d(3, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1))
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (res_0): ResBlock(
    (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (res_1): ResBlock(
    (conv1): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn1): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (conv2): Conv2d(128, 128, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
    (bn2): BatchNorm2d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  

In [109]:
with torch.no_grad():
    leaf = root.select_leaf()
    encoded_s = ed.encode_board(leaf.game); encoded_s = encoded_s.transpose(2,0,1)
    encoded_s = torch.from_numpy(encoded_s).float().cuda()
    child_priors, value_estimate = net(encoded_s)
    child_priors = child_priors.detach().cpu().numpy().reshape(-1)
    value_estimate = value_estimate.item()
    if leaf.game.check_winner() == True or leaf.game.actions() == []: # if somebody won or draw
        leaf.backup(value_estimate) 
#         continue
    # expansion
    leaf.expand(child_priors) # need to make sure valid moves
    # backup
    leaf.backup(value_estimate)

[60, 61, 62, 69, 70, 71, 78, 79, 80]


In [112]:
root.children

{69: <__main__.UCTNode at 0x7fe3651b4310>}

In [110]:
root.number_visits

2.0

In [111]:
root.child_number_visits

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [6]:
with torch.no_grad():
    current_board = c_board()
    checkmate = False
    board_state = copy.deepcopy(ed.encode_board(current_board))

In [81]:
root = UCTNode(current_board, move=None, parent=DummyNode())

In [101]:
leaf = root.select_leaf()

In [102]:
encoded_s = ed.encode_board(leaf.game)
encoded_s = encoded_s.transpose(2,0,1)
encoded_s = torch.from_numpy(encoded_s).float().cuda()

In [103]:
child_priors, value_estimate = net(encoded_s)

In [104]:
child_priors

tensor([[0.0166, 0.0114, 0.0062, 0.0139, 0.0111, 0.0098, 0.0119, 0.0095, 0.0156,
         0.0173, 0.0167, 0.0164, 0.0206, 0.0140, 0.0114, 0.0119, 0.0127, 0.0074,
         0.0112, 0.0067, 0.0185, 0.0100, 0.0075, 0.0142, 0.0132, 0.0257, 0.0096,
         0.0068, 0.0139, 0.0154, 0.0113, 0.0103, 0.0081, 0.0060, 0.0089, 0.0051,
         0.0146, 0.0067, 0.0070, 0.0076, 0.0263, 0.0108, 0.0109, 0.0080, 0.0164,
         0.0155, 0.0103, 0.0213, 0.0234, 0.0067, 0.0081, 0.0119, 0.0070, 0.0133,
         0.0173, 0.0082, 0.0245, 0.0085, 0.0095, 0.0141, 0.0157, 0.0143, 0.0107,
         0.0120, 0.0075, 0.0081, 0.0077, 0.0158, 0.0066, 0.0170, 0.0132, 0.0125,
         0.0132, 0.0091, 0.0128, 0.0080, 0.0055, 0.0196, 0.0203, 0.0104, 0.0154]],
       device='cuda:0', grad_fn=<ExpBackward>)

In [86]:
value_estimate

tensor([[-0.2636]], device='cuda:0', grad_fn=<TanhBackward>)

In [87]:
child_priors = child_priors.detach().cpu().numpy().reshape(-1)
value_estimate = value_estimate.item()

In [88]:
child_priors

array([0.01705102, 0.00777669, 0.0063078 , 0.01867882, 0.01054201,
       0.00560169, 0.01020111, 0.01935214, 0.0099953 , 0.01636836,
       0.01757073, 0.01436909, 0.02292205, 0.00502619, 0.02155052,
       0.01036641, 0.01796573, 0.00998601, 0.01287861, 0.01351345,
       0.01116304, 0.01148709, 0.00629348, 0.02543472, 0.01290886,
       0.02450569, 0.01101202, 0.00904266, 0.00964045, 0.01190577,
       0.0127175 , 0.00340463, 0.00856017, 0.00483537, 0.01959443,
       0.00614132, 0.02352763, 0.01221078, 0.0100853 , 0.00952635,
       0.01352199, 0.01342555, 0.01011256, 0.00559576, 0.01739274,
       0.01694698, 0.01285821, 0.01454341, 0.01055109, 0.01468434,
       0.00845387, 0.00930174, 0.01065725, 0.01349898, 0.01066831,
       0.01830662, 0.01676542, 0.01358381, 0.00430858, 0.01072281,
       0.01295201, 0.00920067, 0.00989054, 0.01520835, 0.01231836,
       0.01146843, 0.00903359, 0.00904995, 0.00767214, 0.01912075,
       0.00556602, 0.00835548, 0.00842852, 0.01634807, 0.01007

In [89]:
leaf.game.check_winner()

False

In [90]:
leaf.game.actions()

[(6, 6), (6, 7), (6, 8), (7, 6), (7, 7), (7, 8), (8, 6), (8, 7), (8, 8)]

In [91]:
valid_moves = leaf.game.actions()

In [94]:
leaf.action_idxes

[60, 61, 62, 69, 70, 71, 78, 79, 80]

In [93]:
leaf.expand(child_priors)

[60, 61, 62, 69, 70, 71, 78, 79, 80]


In [96]:
leaf.backup(value_estimate)

In [97]:
leaf.children

{}

In [98]:
leaf.child_priors

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03815109, 0.03498515, 0.03311222, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04315301,
       0.03034694, 0.03570307, 0.        , 0.        , 0.     

In [99]:
leaf.child_total_value

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [100]:
leaf.child_number_visits

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], dtype=float32)

In [95]:
leaf.child_priors

array([0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.03815109, 0.03498515, 0.03311222, 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.04315301,
       0.03034694, 0.03570307, 0.        , 0.        , 0.     

In [21]:
def return_winner(winner):
    if winner == "O" or winner == "X":
        print(1)
        return True
    elif winner == "tie":
        print(2)
        return winner
    else:
        return False

In [22]:
winner = None

In [20]:
winner == "O" or "X"

'X'

In [23]:
return_winner(winner=None)

False

In [23]:
leaf.game.mega_board

array([[' ', ' ', ' '],
       [' ', ' ', ' '],
       [' ', ' ', ' ']], dtype='<U32')

In [24]:
leaf.game.current_board

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U32')

In [23]:
y = check_ninebox(leaf.game.mega_board)

In [24]:
y

In [21]:
def check_ninebox(mat):
    """
    This function can be use to check the small nine-box \
            or the large nine-box.
    input: mat: a matrix of 3x3
    """
    # look for rows, columns, diagnols
    for i in range(3):
        if mat[i,0] == mat[i,1] == mat[i,2] != ' ':
            return mat[i,0]
        if mat[0,i] == mat[1,i] == mat[2,i] != ' ':
            return mat[0,i]
    if mat[0,0] == mat[1,1] == mat[2,2] != ' ':
        return mat[0,0]
    if mat[0,2] == mat[1,1] == mat[2,0] != ' ':
        return mat[1,1]

    # look for tie
    count = 0
    for i in range(3):
        for j in range(3):
            if mat[i,j] != ' ':
                count += 1
    if count == 9:
        return 'tie'
    else:
        return None

In [80]:
class UCTNode():
    def __init__(self, game, move, parent=None):
        self.game = game # state s
        self.move = move # action index
        self.is_expanded = False
        self.parent = parent  
        self.children = {}
        self.child_priors = np.zeros([81], dtype=np.float32)
        self.child_total_value = np.zeros([81], dtype=np.float32)
        self.child_number_visits = np.zeros([81], dtype=np.float32)
        self.action_idxes = []
        
    @property
    def number_visits(self):
        return self.parent.child_number_visits[self.move]

    @number_visits.setter
    def number_visits(self, value):
        self.parent.child_number_visits[self.move] = value
    
    @property
    def total_value(self):
        return self.parent.child_total_value[self.move]
    
    @total_value.setter
    def total_value(self, value):
        self.parent.child_total_value[self.move] = value
    
    def child_Q(self):
        return self.child_total_value / (1 + self.child_number_visits)
    
    def child_U(self):
        return math.sqrt(self.number_visits) * (
            abs(self.child_priors) / (1 + self.child_number_visits))
    
    def best_child(self):
        if self.action_idxes != []:
            bestmove = self.child_Q() + self.child_U()
            bestmove = self.action_idxes[np.argmax(bestmove[self.action_idxes])]
        else:
            bestmove = np.argmax(self.child_Q() + self.child_U())
        return bestmove
    
    def select_leaf(self):
        current = self
        while current.is_expanded:
            best_move = current.best_child()
            current = current.maybe_add_child(best_move)
        return current
    
    def add_dirichlet_noise(self,action_idxs,child_priors):
        valid_child_priors = child_priors[action_idxs] # select only legal moves entries in child_priors array
        valid_child_priors = 0.75*valid_child_priors + 0.25*np.random.dirichlet(np.zeros([len(valid_child_priors)], \
                                                                                          dtype=np.float32)+192)
        child_priors[action_idxs] = valid_child_priors
        return child_priors
    
    def expand(self, child_priors):
        self.is_expanded = True
        action_idxs = self.game.actions()
        c_p = child_priors
        if action_idxs == []:
            self.is_expanded = False
        else:
            for i,j in action_idxs:
                self.action_idxes.append(i*9+j)
        print(self.action_idxes)
        #self.action_idxes = action_idxs
        #for i in range(9):
        #    for j in range(9):
        #        if (i,j) not in action_idxs:
        #            c_p[i,j] = 0.00000
        c_p[[i for i in range(len(child_priors)) if i not in self.action_idxes]] = 0.000000000 # mask all illegal actions
        if self.parent.parent == None: # add dirichlet noise to child_priors in root node
            c_p = self.add_dirichlet_noise(self.action_idxes,c_p)
        self.child_priors = c_p
    
    def decode_n_move_pieces(self,board,move):
        move = (move//9, move&9)
        board.drop_piece(move)
        return board
            
    def maybe_add_child(self, move):
        if move not in self.children:
            copy_board = copy.deepcopy(self.game) # make copy of board
            copy_board = self.decode_n_move_pieces(copy_board,move)
            self.children[move] = UCTNode(
              copy_board, move, parent=self)
        return self.children[move]
    
    def backup(self, value_estimate: float):
        current = self
        while current.parent is not None:
            current.number_visits += 1
            if current.game.player == 1: # same as current.parent.game.player = 0
                current.total_value += (1*value_estimate) # value estimate +1 = O wins
            elif current.game.player == 0: # same as current.parent.game.player = 1
                current.total_value += (-1*value_estimate)
            current = current.parent

In [8]:
class DummyNode(object):
    def __init__(self):
        self.parent = None
        self.child_total_value = collections.defaultdict(float)
        self.child_number_visits = collections.defaultdict(float)